kind: Component
apiVersion: backstage.io/v1alpha1
metadata:
  name: Hybrid_FCM_Notifications
  title: Hybrid FCM Notifications
  tags: []
  annotations:
    harness.io/project-url: https://app.harness.io/ng/account/AdAW8A4QTgq3YOM_suuuEQ/home/orgs/Teaching_and_Learning/projects/Mobile_Portal/details
    harness.io/cd-serviceId: Hybrid_FCM_Notifications
    harness.io/services: |
      Hybrid_FCM_Notifications: https://app.harness.io/ng/account/AdAW8A4QTgq3YOM_suuuEQ/cd/orgs/Teaching_and_Learning/projects/Mobile_Portal/services/Hybrid_FCM_Notifications
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: Mobile_Portal

