kind: Component
apiVersion: backstage.io/v1alpha1
metadata:
  name: Mobile_DE_Connector
  title: Mobile DE Connector
  tags: []
  annotations:
    harness.io/project-url: https://app.harness.io/ng/account/AdAW8A4QTgq3YOM_suuuEQ/home/orgs/Teaching_and_Learning/projects/Mobile_Portal/details
    harness.io/cd-serviceId: Mobile_DE_Connector
    harness.io/services: |
      Mobile_DE_Connector: https://app.harness.io/ng/account/AdAW8A4QTgq3YOM_suuuEQ/cd/orgs/Teaching_and_Learning/projects/Mobile_Portal/services/Mobile_DE_Connector
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: Mobile_Portal

