kind: Component
apiVersion: backstage.io/v1alpha1
metadata:
  name: testr
  title: testr
  tags: []
  annotations:
    harness.io/project-url: https://app.harness.io/ng/account/AdAW8A4QTgq3YOM_suuuEQ/home/orgs/Tech_Foundations/projects/AWS_IaC/details
    harness.io/cd-serviceId: testr
    harness.io/services: |
      testr: https://app.harness.io/ng/account/AdAW8A4QTgq3YOM_suuuEQ/cd/orgs/Tech_Foundations/projects/AWS_IaC/services/testr
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: AWS_IaC

